### ISSUE TITLE
Since yesterday 15th March 2022 the Kodi Addon isnt working anymore

### ISSUE THREAD

**Issue by elschmidtorado** [maxgalbu/xbmc.plugin.video.nba#113]
Hi Ivan,

i use the addon everyday and i recognized yesterday that if i want to start a archived game, like every day :-),
i get an error from Kodi. Can you confirm this?? 
Is there anything that i can do for u to solve the problem???

thx

**Comment by elschmidtorado** [comment]
thats from log

2022-03-16 18:31:04.530 T:3494867840   ERROR: EXCEPTION: XBMC is not playing any file
2022-03-16 18:31:16.279 T:4086427712   ERROR: Previous line repeats 11 times.
2022-03-16 18:31:16.279 T:4086427712   ERROR: Control 55 in window 10025 has been asked to focus, but it can't
2022-03-16 18:31:16.372 T:3562009472   ERROR: CCurlFile::Stat - Failed: Couldn't resolve host name(6) for http://smb.cdnllnwnl.neulion.com/u/nba/nba/thumbs/dl/14510_pc.jpg
2022-03-16 18:31:16.542 T:3494867840   ERROR: EXCEPTION: XBMC is not playing any file
2022-03-16 18:31:19.617 T:4086427712   ERROR: Previous line repeats 3 times.
2022-03-16 18:31:19.617 T:4086427712   ERROR: Control 55 in window 10025 has been asked to focus, but it can't
2022-03-16 18:31:19.699 T:3486475136   ERROR: CCurlFile::Stat - Failed: Couldn't resolve host name(6) for http://smb.cdnllnwnl.neulion.com/u/nba/nba/thumbs/dl/14510_pc.jpg
2022-03-16 18:31:20.577 T:3494867840   ERROR: EXCEPTION: XBMC is not playing any file
2022-03-16 18:32:23.086 T:3742315392   ERROR: Previous line repeats 61 times.
2022-03-16 18:32:23.086 T:3742315392  NOTICE: ES: Client  from ::ffff:192.168.178.81 timed out
2022-03-16 18:32:23.194 T:3494867840   ERROR: EXCEPTION: XBMC is not playing any file
2022-03-16 18:32:38.644 T:4086427712   ERROR: Previous line repeats 15 times.
2022-03-16 18:32:38.644 T:4086427712  NOTICE: NFS is idle. Closing the remaining connections.
2022-03-16 18:32:39.251 T:3494867840   ERROR: EXCEPTION: XBMC is not playing any file
2022-03-16 18:32:40.328 T:3384759168   ERROR: Previous line repeats 1 times.
2022-03-16 18:32:40.328 T:3384759168 WARNING: Attempt to use invalid handle 18
2022-03-16 18:32:40.475 T:3393151872 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.nba/?game_state=3&name=Full+game%2C+home+feed+%28Pelicans%29&url=&start_time=1647388807000&video_id=0022101032&video_type=archive&mode=playgame&duration=8567000&video_ishomefeed=1
2022-03-16 18:32:40.475 T:3393151872   ERROR: InputStream: Error opening, plugin://plugin.video.nba/?game_state=3&name=Full+game%2C+home+feed+%28Pelicans%29&url=&start_time=1647388807000&video_id=0022101032&video_type=archive&mode=playgame&duration=8567000&video_ishomefeed=1
2022-03-16 18:32:40.481 T:3405767552 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.nba/?game_state=3&name=Full+game%2C+away+feed+%28Suns%29&url=&start_time=1647388807000&video_id=0022101032&video_type=archive&mode=playgame&duration=8567000&video_ishomefeed=0
2022-03-16 18:32:40.481 T:3405767552   ERROR: InputStream: Error opening, plugin://plugin.video.nba/?game_state=3&name=Full+game%2C+away+feed+%28Suns%29&url=&start_time=1647388807000&video_id=0022101032&video_type=archive&mode=playgame&duration=8567000&video_ishomefeed=0
2022-03-16 18:32:40.483 T:3405767552 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.nba/?game_state=3&name=Camera+12%3A+Audio+Home&camera_number=12&url=&start_time=1647388807000&video_id=0022101032&video_type=archive&mode=playgame&duration=8567000
2022-03-16 18:32:40.484 T:3405767552   ERROR: InputStream: Error opening, plugin://plugin.video.nba/?game_state=3&name=Camera+12%3A+Audio+Home&camera_number=12&url=&start_time=1647388807000&video_id=0022101032&video_type=archive&mode=playgame&duration=8567000
2022-03-16 18:32:40.486 T:3393151872 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.nba/?game_state=3&name=Camera+15%3A+Audio+Away+SAP&camera_number=15&url=&start_time=1647388807000&video_id=0022101032&video_type=archive&mode=playgame&duration=8567000
2022-03-16 18:32:40.487 T:3393151872   ERROR: InputStream: Error opening, plugin://plugin.video.nba/?game_state=3&name=Camera+15%3A+Audio+Away+SAP&camera_number=15&url=&start_time=1647388807000&video_id=0022101032&video_type=archive&mode=playgame&duration=8567000
2022-03-16 18:32:40.497 T:3405767552 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.nba/?game_state=3&name=Camera+16%3A+Mobile+View&camera_number=16&url=&start_time=1647388807000&video_id=0022101032&video_type=archive&mode=playgame&duration=8567000
2022-03-16 18:32:40.497 T:3405767552   ERROR: InputStream: Error opening, plugin://plugin.video.nba/?game_state=3&name=Camera+16%3A+Mobile+View&camera_number=16&url=&start_time=1647388807000&video_id=0022101032&video_type=archive&mode=playgame&duration=8567000
2022-03-16 18:32:40.500 T:3405767552 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.nba/?game_state=3&name=Camera+25%3A+Korean+%28SPOTV%29&camera_number=25&url=&start_time=1647388807000&video_id=0022101032&video_type=archive&mode=playgame&duration=8567000
2022-03-16 18:32:40.500 T:3405767552   ERROR: InputStream: Error opening, plugin://plugin.video.nba/?game_state=3&name=Camera+25%3A+Korean+%28SPOTV%29&camera_number=25&url=&start_time=1647388807000&video_id=0022101032&video_type=archive&mode=playgame&duration=8567000
2022-03-16 18:32:40.503 T:3405767552 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.nba/?game_state=3&name=Camera+56%3A+NBA+TV&camera_number=56&url=&start_time=1647388807000&video_id=0022101032&video_type=archive&mode=playgame&duration=8567000
2022-03-16 18:32:40.503 T:3405767552   ERROR: InputStream: Error opening, plugin://plugin.video.nba/?game_state=3&name=Camera+56%3A+NBA+TV&camera_number=56&url=&start_time=1647388807000&video_id=0022101032&video_type=archive&mode=playgame&duration=8567000
2022-03-16 18:32:40.505 T:3393151872 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.nba/?game_state=3&mode=playgame&url=&video_id=0022101032&video_type=condensed&name=Condensed+game
2022-03-16 18:32:40.505 T:3393151872   ERROR: InputStream: Error opening, plugin://plugin.video.nba/?game_state=3&mode=playgame&url=&video_id=0022101032&video_type=condensed&name=Condensed+game
2022-03-16 18:32:41.253 T:3494867840   ERROR: EXCEPTION: XBMC is not playing any file
2022-03-16 18:32:44.343 T:4086427712   ERROR: Previous line repeats 3 times.
2022-03-16 18:32:44.343 T:4086427712  NOTICE: VideoPlayer::OpenFile: plugin://plugin.video.nba/?game_state=3&name=Full+game%2C+home+feed+%28Pelicans%29&url=&start_time=1647388807000&video_id=0022101032&video_type=archive&mode=playgame&duration=8567000&video_ishomefeed=1
2022-03-16 18:32:44.345 T:3553616768  NOTICE: Creating InputStream
2022-03-16 18:32:44.354 T:3553616768 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.nba/?game_state=3&name=Full+game%2C+home+feed+%28Pelicans%29&url=&start_time=1647388807000&video_id=0022101032&video_type=archive&mode=playgame&duration=8567000&video_ishomefeed=1
2022-03-16 18:32:44.354 T:3553616768   ERROR: CVideoPlayer::OpenInputStream - error opening [plugin://plugin.video.nba/?game_state=3&name=Full+game%2C+home+feed+%28Pelicans%29&url=&start_time=1647388807000&video_id=0022101032&video_type=archive&mode=playgame&duration=8567000&video_ishomefeed=1]
2022-03-16 18:32:44.354 T:3553616768  NOTICE: CVideoPlayer::OnExit()
2022-03-16 18:32:44.519 T:4086427712  NOTICE: CVideoPlayer::CloseFile()
2022-03-16 18:32:44.519 T:4086427712  NOTICE: VideoPlayer: waiting for threads to exit
2022-03-16 18:32:44.519 T:4086427712  NOTICE: VideoPlayer: finished waiting
2022-03-16 18:32:45.258 T:3494867840   ERROR: EXCEPTION: XBMC is not playing any file
2022-03-16 18:32:47.387 T:3393151872   ERROR: Previous line repeats 2 times.
2022-03-16 18:32:47.387 T:3393151872 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.nba/?game_state=3&name=Full+game%2C+home+feed+%28Pelicans%29&url=&start_time=1647388807000&video_id=0022101032&video_type=archive&mode=playgame&duration=8567000&video_ishomefeed=1
2022-03-16 18:32:47.387 T:3393151872   ERROR: InputStream: Error opening, plugin://plugin.video.nba/?game_state=3&name=Full+game%2C+home+feed+%28Pelicans%29&url=&start_time=1647388807000&video_id=0022101032&video_type=archive&mode=playgame&duration=8567000&video_ishomefeed=1
2022-03-16 18:32:47.394 T:3393151872 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.nba/?game_state=3&mode=playgame&url=&video_id=0022101032&video_type=condensed&name=Condensed+game
2022-03-16 18:32:47.402 T:3393151872   ERROR: InputStream: Error opening, plugin://plugin.video.nba/?game_state=3&mode=playgame&url=&video_id=0022101032&video_type=condensed&name=Condensed+game
2022-03-16 18:32:47.407 T:3393151872 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.nba/?game_state=3&name=Camera+56%3A+NBA+TV&camera_number=56&url=&start_time=1647388807000&video_id=0022101032&video_type=archive&mode=playgame&duration=8567000
2022-03-16 18:32:47.407 T:3393151872   ERROR: InputStream: Error opening, plugin://plugin.video.nba/?game_state=3&name=Camera+56%3A+NBA+TV&camera_number=56&url=&start_time=1647388807000&video_id=0022101032&video_type=archive&mode=playgame&duration=8567000
2022-03-16 18:32:47.412 T:3393151872 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.nba/?game_state=3&name=Camera+25%3A+Korean+%28SPOTV%29&camera_number=25&url=&start_time=1647388807000&video_id=0022101032&video_type=archive&mode=playgame&duration=8567000
2022-03-16 18:32:47.417 T:3393151872   ERROR: InputStream: Error opening, plugin://plugin.video.nba/?game_state=3&name=Camera+25%3A+Korean+%28SPOTV%29&camera_number=25&url=&start_time=1647388807000&video_id=0022101032&video_type=archive&mode=playgame&duration=8567000
2022-03-16 18:32:47.421 T:3393151872 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.nba/?game_state=3&name=Camera+16%3A+Mobile+View&camera_number=16&url=&start_time=1647388807000&video_id=0022101032&video_type=archive&mode=playgame&duration=8567000
2022-03-16 18:32:47.422 T:3393151872   ERROR: InputStream: Error opening, plugin://plugin.video.nba/?game_state=3&name=Camera+16%3A+Mobile+View&camera_number=16&url=&start_time=1647388807000&video_id=0022101032&video_type=archive&mode=playgame&duration=8567000
2022-03-16 18:32:47.426 T:3393151872 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.nba/?game_state=3&name=Camera+15%3A+Audio+Away+SAP&camera_number=15&url=&start_time=1647388807000&video_id=0022101032&video_type=archive&mode=playgame&duration=8567000
2022-03-16 18:32:47.426 T:3393151872   ERROR: InputStream: Error opening, plugin://plugin.video.nba/?game_state=3&name=Camera+15%3A+Audio+Away+SAP&camera_number=15&url=&start_time=1647388807000&video_id=0022101032&video_type=archive&mode=playgame&duration=8567000
2022-03-16 18:32:47.431 T:3393151872 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.nba/?game_state=3&name=Camera+12%3A+Audio+Home&camera_number=12&url=&start_time=1647388807000&video_id=0022101032&video_type=archive&mode=playgame&duration=8567000
2022-03-16 18:32:47.431 T:3393151872   ERROR: InputStream: Error opening, plugin://plugin.video.nba/?game_state=3&name=Camera+12%3A+Audio+Home&camera_number=12&url=&start_time=1647388807000&video_id=0022101032&video_type=archive&mode=playgame&duration=8567000
2022-03-16 18:32:47.435 T:3393151872 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.nba/?game_state=3&name=Full+game%2C+away+feed+%28Suns%29&url=&start_time=1647388807000&video_id=0022101032&video_type=archive&mode=playgame&duration=8567000&video_ishomefeed=0
2022-03-16 18:32:47.435 T:3393151872   ERROR: InputStream: Error opening, plugin://plugin.video.nba/?game_state=3&name=Full+game%2C+away+feed+%28Suns%29&url=&start_time=1647388807000&video_id=0022101032&video_type=archive&mode=playgame&duration=8567000&video_ishomefeed=0
2022-03-16 18:32:48.368 T:3494867840   ERROR: EXCEPTION: XBMC is not playing any file
2022-03-16 18:32:49.535 T:3393151872   ERROR: Previous line repeats 1 times.
2022-03-16 18:32:49.535 T:3393151872   ERROR: CCurlFile::Stat - Failed: Couldn't resolve host name(6) for http://smb.cdnllnwnl.neulion.com/u/nba/nba/thumbs/dl/14510_pc.jpg
2022-03-16 18:32:50.439 T:3494867840   ERROR: EXCEPTION: XBMC is not playing any file
2022-03-16 18:33:46.481 T:4086427712   ERROR: Previous line repeats 55 times.
2022-03-16 18:33:46.481 T:4086427712   ERROR: Control 55 in window 10025 has been asked to focus, but it can't
2022-03-16 18:33:46.494 T:3494867840   ERROR: EXCEPTION: XBMC is not playing any file
2022-03-16 18:33:46.680 T:3405767552   ERROR: CCurlFile::Stat - Failed: Couldn't resolve host name(6) for http://smb.cdnllnwnl.neulion.com/u/nba/nba/thumbs/dl/14510_pc.jpg
2022-03-16 18:33:47.496 T:3494867840   ERROR: EXCEPTION: XBMC is not playing any file
2022-03-16 18:33:53.824 T:3432719232   ERROR: Previous line repeats 6 times.
2022-03-16 18:33:53.824 T:3432719232 WARNING: Attempt to use invalid handle 27
2022-03-16 18:33:53.963 T:3384759168 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.nba/?game_state=3&name=Full+game%2C+home+feed+%28Pelicans%29&url=&start_time=1647388807000&video_id=0022101032&video_type=archive&mode=playgame&duration=8567000&video_ishomefeed=1
2022-03-16 18:33:53.963 T:3384759168   ERROR: InputStream: Error opening, plugin://plugin.video.nba/?game_state=3&name=Full+game%2C+home+feed+%28Pelicans%29&url=&start_time=1647388807000&video_id=0022101032&video_type=archive&mode=playgame&duration=8567000&video_ishomefeed=1
2022-03-16 18:33:53.966 T:3384759168 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.nba/?game_state=3&name=Full+game%2C+away+feed+%28Suns%29&url=&start_time=1647388807000&video_id=0022101032&video_type=archive&mode=playgame&duration=8567000&video_ishomefeed=0
2022-03-16 18:33:53.966 T:3384759168   ERROR: InputStream: Error opening, plugin://plugin.video.nba/?game_state=3&name=Full+game%2C+away+feed+%28Suns%29&url=&start_time=1647388807000&video_id=0022101032&video_type=archive&mode=playgame&duration=8567000&video_ishomefeed=0
2022-03-16 18:33:53.968 T:3405767552 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.nba/?game_state=3&name=Camera+12%3A+Audio+Home&camera_number=12&url=&start_time=1647388807000&video_id=0022101032&video_type=archive&mode=playgame&duration=8567000
2022-03-16 18:33:53.968 T:3405767552   ERROR: InputStream: Error opening, plugin://plugin.video.nba/?game_state=3&name=Camera+12%3A+Audio+Home&camera_number=12&url=&start_time=1647388807000&video_id=0022101032&video_type=archive&mode=playgame&duration=8567000
2022-03-16 18:33:53.971 T:3405767552 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.nba/?game_state=3&name=Camera+15%3A+Audio+Away+SAP&camera_number=15&url=&start_time=1647388807000&video_id=0022101032&video_type=archive&mode=playgame&duration=8567000
2022-03-16 18:33:53.971 T:3405767552   ERROR: InputStream: Error opening, plugin://plugin.video.nba/?game_state=3&name=Camera+15%3A+Audio+Away+SAP&camera_number=15&url=&start_time=1647388807000&video_id=0022101032&video_type=archive&mode=playgame&duration=8567000
2022-03-16 18:33:53.974 T:3384759168 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.nba/?game_state=3&name=Camera+16%3A+Mobile+View&camera_number=16&url=&start_time=1647388807000&video_id=0022101032&video_type=archive&mode=playgame&duration=8567000
2022-03-16 18:33:53.974 T:3384759168   ERROR: InputStream: Error opening, plugin://plugin.video.nba/?game_state=3&name=Camera+16%3A+Mobile+View&camera_number=16&url=&start_time=1647388807000&video_id=0022101032&video_type=archive&mode=playgame&duration=8567000
2022-03-16 18:33:53.977 T:3384759168 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.nba/?game_state=3&name=Camera+25%3A+Korean+%28SPOTV%29&camera_number=25&url=&start_time=1647388807000&video_id=0022101032&video_type=archive&mode=playgame&duration=8567000
2022-03-16 18:33:53.978 T:3384759168   ERROR: InputStream: Error opening, plugin://plugin.video.nba/?game_state=3&name=Camera+25%3A+Korean+%28SPOTV%29&camera_number=25&url=&start_time=1647388807000&video_id=0022101032&video_type=archive&mode=playgame&duration=8567000
2022-03-16 18:33:53.981 T:3405767552 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.nba/?game_state=3&name=Camera+56%3A+NBA+TV&camera_number=56&url=&start_time=1647388807000&video_id=0022101032&video_type=archive&mode=playgame&duration=8567000
2022-03-16 18:33:53.981 T:3405767552   ERROR: InputStream: Error opening, plugin://plugin.video.nba/?game_state=3&name=Camera+56%3A+NBA+TV&camera_number=56&url=&start_time=1647388807000&video_id=0022101032&video_type=archive&mode=playgame&duration=8567000
2022-03-16 18:33:53.983 T:3405767552 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.nba/?game_state=3&mode=playgame&url=&video_id=0022101032&video_type=condensed&name=Condensed+game
2022-03-16 18:33:53.983 T:3405767552   ERROR: InputStream: Error opening, plugin://plugin.video.nba/?game_state=3&mode=playgame&url=&video_id=0022101032&video_type=condensed&name=Condensed+game
2022-03-16 18:33:54.613 T:3494867840   ERROR: EXCEPTION: XBMC is not playing any file
2022-03-16 18:33:58.946 T:3432719232   ERROR: Previous line repeats 4 times.
2022-03-16 18:33:58.946 T:3432719232   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeDecodeError'>
                                            Error Contents: 'ascii' codec can't decode byte 0xe2 in position 58437: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.nba/main.py", line 12, in <module>
                                                from leaguepass import *
                                              File "/storage/.kodi/addons/plugin.video.nba/src/leaguepass.py", line 79, in <module>
                                                play_game()
                                              File "/storage/.kodi/addons/plugin.video.nba/src/games.py", line 322, in play_game
                                                common.play(game)
                                              File "/storage/.kodi/addons/plugin.video.nba/src/common.py", line 32, in play
                                                if is_helper.check_inputstream():
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 407, in check_inputstream
                                                return self._check_drm()
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 359, in _check_drm
                                                return self._check_widevine()
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 329, in _check_widevine
                                                self._update_widevine()
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 288, in _update_widevine
                                                latest_version = latest_widevine_version()
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/widevine/widevine.py", line 164, in latest_widevine_version
                                                devices = chromeos_config()
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/widevine/arm.py", line 63, in chromeos_config
                                                return json.loads(http_get(config.CHROMEOS_RECOVERY_URL))
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/utils.py", line 73, in http_get
                                                return content.decode()
                                            UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 58437: ordinal not in range(128)
                                            -->End of Python script error report<--
2022-03-16 18:33:59.121 T:4086427712   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.nba/?game_state=3&name=Full+game%2C+home+feed+%28Pelicans%29&url=&start_time=1647388807000&video_id=0022101032&video_type=archive&mode=playgame&duration=8567000&video_ishomefeed=1]
2022-03-16 18:33:59.147 T:3384759168 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.nba/?game_state=3&name=Full+game%2C+home+feed+%28Pelicans%29&url=&start_time=1647388807000&video_id=0022101032&video_type=archive&mode=playgame&duration=8567000&video_ishomefeed=1
2022-03-16 18:33:59.147 T:3384759168   ERROR: InputStream: Error opening, plugin://plugin.video.nba/?game_state=3&name=Full+game%2C+home+feed+%28Pelicans%29&url=&start_time=1647388807000&video_id=0022101032&video_type=archive&mode=playgame&duration=8567000&video_ishomefeed=1
2022-03-16 18:33:59.149 T:3384759168 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.nba/?game_state=3&name=Full+game%2C+away+feed+%28Suns%29&url=&start_time=1647388807000&video_id=0022101032&video_type=archive&mode=playgame&duration=8567000&video_ishomefeed=0
2022-03-16 18:33:59.149 T:3384759168   ERROR: InputStream: Error opening, plugin://plugin.video.nba/?game_state=3&name=Full+game%2C+away+feed+%28Suns%29&url=&start_time=1647388807000&video_id=0022101032&video_type=archive&mode=playgame&duration=8567000&video_ishomefeed=0
2022-03-16 18:33:59.152 T:3405767552 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.nba/?game_state=3&name=Camera+12%3A+Audio+Home&camera_number=12&url=&start_time=1647388807000&video_id=0022101032&video_type=archive&mode=playgame&duration=8567000
2022-03-16 18:33:59.152 T:3405767552   ERROR: InputStream: Error opening, plugin://plugin.video.nba/?game_state=3&name=Camera+12%3A+Audio+Home&camera_number=12&url=&start_time=1647388807000&video_id=0022101032&video_type=archive&mode=playgame&duration=8567000
2022-03-16 18:33:59.155 T:3384759168 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.nba/?game_state=3&name=Camera+15%3A+Audio+Away+SAP&camera_number=15&url=&start_time=1647388807000&video_id=0022101032&video_type=archive&mode=playgame&duration=8567000
2022-03-16 18:33:59.155 T:3384759168   ERROR: InputStream: Error opening, plugin://plugin.video.nba/?game_state=3&name=Camera+15%3A+Audio+Away+SAP&camera_number=15&url=&start_time=1647388807000&video_id=0022101032&video_type=archive&mode=playgame&duration=8567000
2022-03-16 18:33:59.158 T:3405767552 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.nba/?game_state=3&name=Camera+16%3A+Mobile+View&camera_number=16&url=&start_time=1647388807000&video_id=0022101032&video_type=archive&mode=playgame&duration=8567000
2022-03-16 18:33:59.158 T:3405767552   ERROR: InputStream: Error opening, plugin://plugin.video.nba/?game_state=3&name=Camera+16%3A+Mobile+View&camera_number=16&url=&start_time=1647388807000&video_id=0022101032&video_type=archive&mode=playgame&duration=8567000
2022-03-16 18:33:59.161 T:3405767552 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.nba/?game_state=3&name=Camera+25%3A+Korean+%28SPOTV%29&camera_number=25&url=&start_time=1647388807000&video_id=0022101032&video_type=archive&mode=playgame&duration=8567000
2022-03-16 18:33:59.161 T:3405767552   ERROR: InputStream: Error opening, plugin://plugin.video.nba/?game_state=3&name=Camera+25%3A+Korean+%28SPOTV%29&camera_number=25&url=&start_time=1647388807000&video_id=0022101032&video_type=archive&mode=playgame&duration=8567000
2022-03-16 18:33:59.164 T:3405767552 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.nba/?game_state=3&name=Camera+56%3A+NBA+TV&camera_number=56&url=&start_time=1647388807000&video_id=0022101032&video_type=archive&mode=playgame&duration=8567000
2022-03-16 18:33:59.164 T:3405767552   ERROR: InputStream: Error opening, plugin://plugin.video.nba/?game_state=3&name=Camera+56%3A+NBA+TV&camera_number=56&url=&start_time=1647388807000&video_id=0022101032&video_type=archive&mode=playgame&duration=8567000
2022-03-16 18:33:59.166 T:3405767552 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.nba/?game_state=3&mode=playgame&url=&video_id=0022101032&video_type=condensed&name=Condensed+game
2022-03-16 18:33:59.166 T:3405767552   ERROR: InputStream: Error opening, plugin://plugin.video.nba/?game_state=3&mode=playgame&url=&video_id=0022101032&video_type=condensed&name=Condensed+game

**Comment by Ansah-98** [comment]
Is it still working
