### ISSUE TITLE
after a Kodi update, games failed to start

### ISSUE THREAD

**Issue by dotslasher** [maxgalbu/xbmc.plugin.video.nba#39]
Hi,

I'm running KODI 17 RC3.

On RC2 the addon worked fine. 
But now when I want to start a game I get the following in my logs:

```
09:04:37.513 T:139767859164928   DEBUG: CPythonInvoker(53, /home/sven/.kodi/addons/plugin.video.nba/leaguepass.py): start processing
09:04:37.564 T:139767859164928   DEBUG: -->Python Interpreter Initialized<--
09:04:37.564 T:139767859164928   DEBUG: CPythonInvoker(53, /home/sven/.kodi/addons/plugin.video.nba/leaguepass.py): the source file to load is "/home/sven/.kodi/addons/plugin.video.nba/leaguepass.py"
09:04:37.564 T:139767859164928   DEBUG: CPythonInvoker(53, /home/sven/.kodi/addons/plugin.video.nba/leaguepass.py): setting the Python path to /home/sven/.kodi/addons/plugin.video.nba:/home/sven/.kodi/addons/script.common.plugin.cache/l$
09:04:37.564 T:139767859164928   DEBUG: CPythonInvoker(53, /home/sven/.kodi/addons/plugin.video.nba/leaguepass.py): entering source directory /home/sven/.kodi/addons/plugin.video.nba
09:04:37.564 T:139767859164928   DEBUG: CPythonInvoker(53, /home/sven/.kodi/addons/plugin.video.nba/leaguepass.py): instantiating addon using automatically obtained id of "plugin.video.nba" dependent on version 2.20.0 of the xbmc.python$
09:04:38.000 T:139768463657344   DEBUG: ------ Window Init (DialogBusy.xml) ------
09:04:38.400 T:139767859164928    INFO: ##### NBA League Pass: Chosen quality_id 0 and target_video_height 72060
09:04:38.406 T:139767859164928   DEBUG: ##### NBA League Pass: the body of publishpoint request is: gt=64&bitrate=1600&plid=09cc5c1c4cf57f4f971621d24c398dd5&type=game&extid=0021600634
09:04:38.445 T:139767859164928   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'urllib2.URLError'>
                                            Error Contents: <urlopen error [Errno 0] Error>
                                            Traceback (most recent call last):
                                              File "/home/sven/.kodi/addons/plugin.video.nba/leaguepass.py", line 80, in <module>
                                                chooseGameVideoMenu()
                                              File "/home/sven/.kodi/addons/plugin.video.nba/games.py", line 327, in chooseGameVideoMenu
                                                highlights_url = getHighlightGameUrl(video_id)
                                              File "/home/sven/.kodi/addons/plugin.video.nba/games.py", line 108, in getHighlightGameUrl
                                                response = urllib2.urlopen(request)
                                              File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
                                                return opener.open(url, data, timeout)
                                              File "/usr/lib/python2.7/urllib2.py", line 429, in open
                                                response = self._open(req, data)
                                              File "/usr/lib/python2.7/urllib2.py", line 447, in _open
                                                '_open', req)
                                              File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
                                                result = func(*args)
                                              File "/usr/lib/python2.7/urllib2.py", line 1241, in https_open
                                                context=self._context)
                                              File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
                                                raise URLError(err)
                                            URLError: <urlopen error [Errno 0] Error>
                                            -->End of Python script error report<--
09:04:38.458 T:139768463657344   DEBUG: ------ Window Init (DialogNotification.xml) ------
09:04:38.563 T:139767859164928    INFO: Python script stopped
09:04:38.563 T:139767859164928   DEBUG: Thread LanguageInvoker 139767859164928 terminating
09:04:38.588 T:139768463657344   ERROR: GetDirectory - Error getting plugin://plugin.video.nba/?game_state=2&has_condensed_game=0&mode=gamechoosevideo&name=2017-01-18%20Thunder%20vs%20Warriors&url&video_hasawayfeed=1&video_id=0021600634$
09:04:38.589 T:139768463657344   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.nba/?game_state=2&has_condensed_game=0&mode=gamechoosevideo&name=2017-01-18%20Thunder%20vs%20Warriors&url&video_hasawayfeed=1&video_id=002160063$
09:04:38.590 T:139768463657344   DEBUG: CGUIMediaWindow::GetDirectory (plugin://plugin.video.nba/?mode=thisweek&name=This%20week&url=archive)
09:04:38.590 T:139768463657344   DEBUG:   ParentPath = [plugin://plugin.video.nba/?mode=archive&name=Archive&url=archive]
09:04:38.599 T:139766582454016   DEBUG: CAddonDatabase::SetLastUsed[plugin.video.nba] took 10 ms
```

**Comment by maxgalbu** [comment]
Sorry, I'm unable to support both release candidates and stable releases :/

**Comment by chovy** [comment]
i have found kodi17 breaks a lot of addons, not just this one. It seems neulion based services.

**Comment by jaydee73** [comment]
Any news here as Kodi v17 final is now available?

**Comment by maxgalbu** [comment]
Is it still not working in kodi v17? It's working for me...
