### ISSUE TITLE
file.close() referenced before assignment

### ISSUE THREAD

**Issue by Aquassaut** [maxgalbu/xbmc.plugin.video.nba#43]
Hey there,

In branch polling service, when installing from zero, [this piece](https://github.com/maxgalbu/xbmc.plugin.video.nba/blob/polling-service/src/shareddata.py#L19) is throwing with a UnboundLocalError:
```
Error Type: <type 'exceptions.UnboundLocalError'>
Error Contents: local variable 'file' referenced before assignment
Traceback (most recent call last):
  File "%APPDATA%\Roaming\Kodi\addons\plugin.video.nba\src\service.py", line 116, in <module>
    main()
  File "%APPDATA%\Roaming\Kodi\addons\plugin.video.nba\src\service.py", line 97, in main
    shared_data.set("playing", {})
  File "%APPDATA%\Roaming\Kodi\addons\plugin.video.nba\src\shareddata.py", line 24, in set
    json_content = self.__getFileContent()
  File "%APPDATA%\Roaming\Kodi\addons\plugin.video.nba\src\shareddata.py", line 19, in __getFileContent
    file.close()
UnboundLocalError: local variable 'file' referenced before assignment
```

I believe something like this would fix it:
```py
def __getFileContent(self):
    try:
        with open(self.file_path) as file:
            file_content = file.read()
    except IOError:
        file_content = "{}"
    return json.loads(file_content)
```

Cheers

**Comment by maxgalbu** [comment]
Thanks, I've added your fix to the branch. Open a pull request if you want next time
