### ISSUE TITLE
Cant open date to play highlights, top plays

### ISSUE THREAD

**Issue by siggijo72** [maxgalbu/xbmc.plugin.video.nba#5]
When I try to click on a date to play highlights or top plays it gives an error:
"NBA League Pass error. Check the error log for more informatiopn."

Example of error message is:
5 T:5292   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <class 'urllib2.HTTPError'>
Error Contents: HTTP Error 404: Not Found
Traceback (most recent call last):
                                              File "C:\Users\Siggi\AppData\Roaming\Kodi\addons\xbmc.plugin.video.nba-master\leaguepass.py", line 83, in <module>
                                                videoMenu(url, mode.replace("videodate", "") )
                                              File "C:\Users\Siggi\AppData\Roaming\Kodi\addons\xbmc.plugin.video.nba-master\videos.py", line 50, in videoMenu
                                                response = urllib2.urlopen(url).read()
                                              File "C:\Program Files\Kodi\system\python\Lib\urllib2.py", line 127, in urlopen
                                                return _opener.open(url, data, timeout)
                                              File "C:\Program Files\Kodi\system\python\Lib\urllib2.py", line 410, in open
                                                response = meth(req, response)
                                              File "C:\Program Files\Kodi\system\python\Lib\urllib2.py", line 523, in http_response
                                                'http', request, response, code, msg, hdrs)
                                              File "C:\Program Files\Kodi\system\python\Lib\urllib2.py", line 448, in error
                                                return self._call_chain(*args)
                                              File "C:\Program Files\Kodi\system\python\Lib\urllib2.py", line 382, in _call_chain
                                                result = func(*args)
                                              File "C:\Program Files\Kodi\system\python\Lib\urllib2.py", line 531, in http_error_default
                                                raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
                                            HTTPError: HTTP Error 404: Not Found
-->End of Python script error report<--

This is version 0.7, started after the end of last season. The other links work fine, nba tv, games etc. Just highlights and top plays not working. Please fix, I love this add-on.

**Comment by maxgalbu** [comment]
Thanks, I'll take a look

**Comment by siggijo72** [comment]
Thanks man...you rock!

**Comment by maxgalbu** [comment]
That was a quick reply :)
