### ISSUE TITLE
Error Contents: No module named base_thread

### ISSUE THREAD

**Issue by dwane3** [maxgalbu/xbmc.plugin.video.nba#58]
When on my windows 7 x64 PC with kodi 16.1 install plugin,this operation with error,plugin do not start:

Error Contents: No module named base_thread
                                            Traceback (most recent call last):
                                              File "C:\Users\�������\AppData\Roaming\Kodi\addons\plugin.video.nba\src\service.py", line 15, in <module>
                                                from base_thread import BaseThread
                                            ImportError: No module named base_thread

My Admin username in cyrillic font (Russia),please insert fixing patch in plugin.
(for example: _addon_path = xbmc.translatePath(_ADDON.getAddonInfo('path')).decode('utf-8')  )

**Comment by maxgalbu** [comment]
Please test my blind fix in commit https://github.com/maxgalbu/xbmc.plugin.video.nba/commit/62d8aed35c7f49777e52728cdc02f73236c996b4 by installing from this zip file: https://github.com/maxgalbu/xbmc.plugin.video.nba/releases/download/nightly-master/plugin.video.nba-master.zip

**Comment by dwane3** [comment]
I am test,sorry,but error..
 Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named base_thread
                                            Traceback (most recent call last):
                                              File "C:\Users\�������\AppData\Roaming\Kodi\addons\plugin.video.nba\src\service.py", line 15, in <module>
                                                from base_thread import BaseThread
                                            ImportError: No module named base_thread
                                            -->End of Python script error report<--
06:44:19 T:4460   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named leaguepass
                                            Traceback (most recent call last):
                                              File "C:\Users\�������\AppData\Roaming\Kodi\addons\plugin.video.nba\main.py", line 9, in <module>
                                                from leaguepass import *
                                            ImportError: No module named leaguepass
                                            -->End of Python script error report<--

**Comment by dwane3** [comment]
nightly version:
 Error Type: <type 'exceptions.IOError'>
                                            Error Contents: (2, 'No such file or directory', u'C:\\Users\\\u0410\u043b\u0435\u043a\u0441\u0435\u0439\\AppData\\Roaming\\Kodi\\addons\\plugin.video.nba\\config\\config.json')
                                            Traceback (most recent call last):
                                              File "C:\Users\�������\AppData\Roaming\Kodi\addons\xbmc.plugin.video.nba-nightly-\src\service.py", line 5, in <module>
                                                import vars
                                              File "C:\Users\�������\AppData\Roaming\Kodi\addons\xbmc.plugin.video.nba-nightly-\src\vars.py", line 50, in <module>
                                                config_json = open(config_path).read()
                                            IOError: (2, 'No such file or directory', u'C:\\Users\\\u0410\u043b\u0435\u043a\u0441\u0435\u0439\\AppData\\Roaming\\Kodi\\addons\\plugin.video.nba\\config\\config.json')
                                            -->End of Python script error report<--

**Comment by dwane3** [comment]
nightly-master:

Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named leaguepass
                                            Traceback (most recent call last):
                                              File "C:\Users\�������\AppData\Roaming\Kodi\addons\xbmc.plugin.video.nba-nightly-master\main.py", line 9, in <module>
                                                from leaguepass import *
                                            ImportError: No module named leaguepass

**Comment by dwane3** [comment]
v. 0.8.3 install without error..

**Comment by maxgalbu** [comment]
Please try again with the zip (this is the commit: https://github.com/maxgalbu/xbmc.plugin.video.nba/commit/1d8a4372740241f762dd838fdabb1477c40dd5f1)

**Comment by dwane3** [comment]
new nightly:
Error Type: <type 'exceptions.IOError'>
                                            Error Contents: (2, 'No such file or directory', u'C:\\Users\\\u0410\u043b\u0435\u043a\u0441\u0435\u0439\\AppData\\Roaming\\Kodi\\addons\\plugin.video.nba\\config\\config.json')
                                            Traceback (most recent call last):
                                              File "C:\Users\�������\AppData\Roaming\Kodi\addons\xbmc.plugin.video.nba-nightly-master\src\service.py", line 5, in <module>
                                                import vars
                                              File "C:\Users\�������\AppData\Roaming\Kodi\addons\xbmc.plugin.video.nba-nightly-master\src\vars.py", line 50, in <module>
                                                config_json = open(config_path).read()
                                            IOError: (2, 'No such file or directory', u'C:\\Users\\\u0410\u043b\u0435\u043a\u0441\u0435\u0439\\AppData\\Roaming\\Kodi\\addons\\plugin.video.nba\\config\\config.json')
                                            -->End of Python script error report<--
18:08:44 T:3012   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IOError'>
                                            Error Contents: (2, 'No such file or directory', u'C:\\Users\\\u0410\u043b\u0435\u043a\u0441\u0435\u0439\\AppData\\Roaming\\Kodi\\addons\\plugin.video.nba\\config\\config.json')
                                            Traceback (most recent call last):
                                              File "C:\Users\�������\AppData\Roaming\Kodi\addons\xbmc.plugin.video.nba-nightly-\src\service.py", line 5, in <module>
                                                import vars
                                              File "C:\Users\�������\AppData\Roaming\Kodi\addons\xbmc.plugin.video.nba-nightly-\src\vars.py", line 50, in <module>
                                                config_json = open(config_path).read()
                                            IOError: (2, 'No such file or directory', u'C:\\Users\\\u0410\u043b\u0435\u043a\u0441\u0435\u0439\\AppData\\Roaming\\Kodi\\addons\\plugin.video.nba\\config\\config.json')
                                            -->End of Python script error report<--
18:08:56 T:7700   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named leaguepass
                                            Traceback (most recent call last):
                                              File "C:\Users\�������\AppData\Roaming\Kodi\addons\xbmc.plugin.video.nba-nightly-\main.py", line 9, in <module>
                                                from leaguepass import *
                                            ImportError: No module named leaguepass

**Comment by maxgalbu** [comment]
Not even github/windows knows how to interpret these chars... how's that possible? What's those ������� chars?

**Comment by maxgalbu** [comment]
Let's try to change the config path.. seems like the one that's failing. https://github.com/maxgalbu/xbmc.plugin.video.nba/commit/89c204df9af2c8002096792259ede284326dd0c8

Try again with the zip please

**Comment by dwane3** [comment]
������� chars=Алексей

Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named base_thread
                                            Traceback (most recent call last):
                                              File "C:\Users\�������\AppData\Roaming\Kodi\addons\xbmc.plugin.video.nba-nightly-master\src\service.py", line 15, in <module>
                                                from base_thread import BaseThread
                                            ImportError: No module named base_thread

**Comment by maxgalbu** [comment]
Hope this is the last :) https://github.com/maxgalbu/xbmc.plugin.video.nba/commit/dbdceb422d01a8841fd356c5f8e018f3a9f752e7

**Comment by dwane3** [comment]
Error,but works!Thanks!

Error Type: <type 'exceptions.IOError'>
                                            Error Contents: (2, 'No such file or directory', 'C:\\Users\\\xd0\x90\xd0\xbb\xd0\xb5\xd0\xba\xd1\x81\xd0\xb5\xd0\xb9\\AppData\\Roaming\\Kodi\\userdata\\addon_data\\plugin.video.nba\\shared_data.json')
                                            Traceback (most recent call last):
                                              File "C:\Users\�������\AppData\Roaming\Kodi\addons\xbmc.plugin.video.nba-nightly-master\src\service.py", line 116, in <module>
                                                main()
                                              File "C:\Users\�������\AppData\Roaming\Kodi\addons\xbmc.plugin.video.nba-nightly-master\src\service.py", line 97, in main
                                                shared_data.set("playing", {})
                                              File "C:\Users\�������\AppData\Roaming\Kodi\addons\xbmc.plugin.video.nba-nightly-master\src\shareddata.py", line 42, in set
                                                file = open(self.file_path, "w")
                                            IOError: (2, 'No such file or directory', 'C:\\Users\\\xd0\x90\xd0\xbb\xd0\xb5\xd0\xba\xd1\x81\xd0\xb5\xd0\xb9\\AppData\\Roaming\\Kodi\\userdata\\addon_data\\plugin.video.nba\\shared_data.json')
                                            -->End of Python script error report<--
