### ISSUE TITLE
Can't play NBA Live TV or any games (archived or live)

### ISSUE THREAD

**Issue by chovy** [maxgalbu/xbmc.plugin.video.nba#61]
I'm using an international account and it has worked fine up until a couple of days ago.

Using version from master.

```
0:31:03.412 T:123145497001984   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IOError'>
                                            Error Contents: (2, 'No such file or directory', '/Users/ettinger/Library/Application Support/Kodi/userdata/addon_data/plugin.video.nba/shared_data.json')
                                            Traceback (most recent call last):
                                              File "/Users/ettinger/Library/Application Support/Kodi/addons/plugin.video.nba/src/service.py", line 116, in <module>
                                                main()
                                              File "/Users/ettinger/Library/Application Support/Kodi/addons/plugin.video.nba/src/service.py", line 97, in main
                                                shared_data.set("playing", {})
                                              File "/Users/ettinger/Library/Application Support/Kodi/addons/plugin.video.nba/src/shareddata.py", line 42, in set
                                                file = open(self.file_path, "w")
                                            IOError: (2, 'No such file or directory', '/Users/ettinger/Library/Application Support/Kodi/userdata/addon_data/plugin.video.nba/shared_data.json')
                                            -->End of Python script error report<--
10:31:44.598 T:123145514786816   ERROR: Previous line repeats 1 times.
10:31:44.598 T:123145514786816   ERROR: ExtractFrame: Could not decode a frame
10:31:47.001 T:140736114500544   ERROR: Control 50 in window 10025 has been asked to focus, but it can't
10:31:53.768 T:123145501294592 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.nba/?url=&mode=nbatvlive&name=Watch+live
10:31:53.768 T:123145501294592   ERROR: InputStream: Error opening, plugin://plugin.video.nba/?url=&mode=nbatvlive&name=Watch+live
10:31:57.195 T:123145497538560   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'group'
                                            Traceback (most recent call last):
                                              File "/Users/ettinger/Library/Application Support/Kodi/addons/plugin.video.nba/main.py", line 9, in <module>
                                                from leaguepass import *
                                              File "/Users/ettinger/Library/Application Support/Kodi/addons/plugin.video.nba/src/leaguepass.py", line 99, in <module>
                                                LiveTV.playLive()
                                              File "/Users/ettinger/Library/Application Support/Kodi/addons/plugin.video.nba/src/nbatvlive.py", line 64, in playLive
                                                video_url = LiveTV.getLiveUrl()
                                              File "/Users/ettinger/Library/Application Support/Kodi/addons/plugin.video.nba/src/nbatvlive.py", line 191, in getLiveUrl
                                                domain = match.group(1)
                                            AttributeError: 'NoneType' object has no attribute 'group'
                                            -->End of Python script error report<--
10:31:57.228 T:140736114500544   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.nba/?url=&mode=nbatvlive&name=Watch+live]
10:31:58.573 T:123145501294592 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.nba/?url=&mode=nbatvlive&name=Watch+live
10:31:58.573 T:123145501294592   ERROR: InputStream: Error opening, plugin://plugin.video.nba/?url=&mode=nbatvlive&name=Watch+live
10:32:01.631 T:123145514786816   ERROR: Unable to find plugin
10:32:01.631 T:140736114500544   ERROR: GetDirectory - Error getting plugin://
10:32:01.632 T:140736114500544   ERROR: CGUIMediaWindow::GetDirectory(plugin://) failed
10:32:17.416 T:123145514250240   ERROR: ExtractFrame: Could not decode a frame
10:34:37.684 T:123145502904320 WARNING: DARWINOSX: underflow (0 vs 4096 bytes)
10:36:27.180 T:123145502367744  NOTICE: virtual bool CAESinkDARWINOSX::Initialize(AEAudioFormat &, std::string &): Opening default device Built-in Output
10:37:36.453 T:123145502904320   ERROR: ExtractFrame: Could not decode a frame
10:37:55.891 T:123145520066560   ERROR: EXCEPTION: XBMC is not playing any file
10:38:10.524 T:140736114500544   ERROR: Previous line repeats 14 times.
10:38:10.524 T:140736114500544   ERROR: Control 50 in window 10025 has been asked to focus, but it can't
10:38:10.946 T:123145520066560   ERROR: EXCEPTION: XBMC is not playing any file
10:38:14.158 T:123145502904320   ERROR: Previous line repeats 3 times.
10:38:14.158 T:123145502904320 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.nba/?url=&mode=nbatvlive&name=Watch+live
10:38:14.158 T:123145502904320   ERROR: InputStream: Error opening, plugin://plugin.video.nba/?url=&mode=nbatvlive&name=Watch+live
10:38:14.961 T:123145520066560   ERROR: EXCEPTION: XBMC is not playing any file
10:38:17.505 T:123145505665024   ERROR: Previous line repeats 2 times.
10:38:17.505 T:123145505665024   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'group'
                                            Traceback (most recent call last):
                                              File "/Users/ettinger/Library/Application Support/Kodi/addons/plugin.video.nba/main.py", line 9, in <module>
                                                from leaguepass import *
                                              File "/Users/ettinger/Library/Application Support/Kodi/addons/plugin.video.nba/src/leaguepass.py", line 99, in <module>
                                                LiveTV.playLive()
                                              File "/Users/ettinger/Library/Application Support/Kodi/addons/plugin.video.nba/src/nbatvlive.py", line 64, in playLive
                                                video_url = LiveTV.getLiveUrl()
                                              File "/Users/ettinger/Library/Application Support/Kodi/addons/plugin.video.nba/src/nbatvlive.py", line 191, in getLiveUrl
                                                domain = match.group(1)
                                            AttributeError: 'NoneType' object has no attribute 'group'
                                            -->End of Python script error report<--
10:38:17.551 T:140736114500544   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.nba/?url=&mode=nbatvlive&name=Watch+live]
10:38:17.974 T:123145520066560   ERROR: EXCEPTION: XBMC is not playing any file
10:38:22.317 T:123145495392256   ERROR: Previous line repeats 4 times.
10:38:22.317 T:123145495392256 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.nba/?url=&mode=nbatvlive&name=Watch+live
10:38:22.317 T:123145495392256   ERROR: InputStream: Error opening, plugin://plugin.video.nba/?url=&mode=nbatvlive&name=Watch+live
10:38:22.991 T:123145520066560   ERROR: EXCEPTION: XBMC is not playing any file
10:38:36.629 T:123145505665024   ERROR: Previous line repeats 13 times.
```

http://paste.ubuntu.com/25747287/

Full log

**Comment by nzeppos** [comment]
I'd expect this is related to https://github.com/maxgalbu/xbmc.plugin.video.nba/issues/60 which not only affects Max's addon, but the official NBA apps as well. I can't want NBA Live TV neither on the latest version of the Xbox One official app, nor on the Android TV one. Clearly the problem stems from Neulion themselves and some changes they've applied only in the last couple of days.

**Comment by nickomaru** [comment]
work

http://puu.sh/xZlDe/9bfc9a4d7f.jpg

**Comment by vishaldasari** [comment]
I am not able to go to NBA league pass international and view games. I simply get a video cannot be played error. Is this happening to others?

**Comment by maxgalbu** [comment]
Let's continue on #60
