### ISSUE TITLE
Can´t watch live in Fire tv stick

### ISSUE THREAD

**Issue by angus1225** [maxgalbu/xbmc.plugin.video.nba#87]
I´m a litlle bit lost since input.adaptative…
Just to know if someone could watch live games in kodi 17.6 in a firetv stick.
I can´t
It seems is going to start, but it dosn´t… doesnt show an error message.
Maybe something is missing in my installation… i dont know

**Comment by MRLB** [comment]
@angus1225 
Try this one:
https://github.com/maxgalbu/xbmc.plugin.video.nba/issues/83#issuecomment-431911656

**Comment by angus1225** [comment]
Thanks @MRLB for your answer.

i tryied with the new zip with the modified gmae.py like you suggested:
 Go to /src/games.py
Change line 245 from
thumbnail_url = utils.generateCombinedThumbnail(v, h)
to
thumbnail_url = ""

but i didnt work.

can you explain it to me better? Maybe i dont understand it well…
Thanks

**Comment by MRLB** [comment]
You Need Kodi 18. Because of DRM it will not work with Kodi 17.6 anymore in Android

**Comment by yzfr1** [comment]
I try this fix and work. But the fix have a problem... I put in config 720P 60FPS and 6000kbs of bitrate, but the stream always set 720P 30FPS and 3000Kbs. Any fix for this?? THX

**Comment by angus1225** [comment]
I tried kodi 18 beta 4. Now I can hear the video but I can't see anything. 
How do you make it @yzfr1 ?

**Comment by yzfr1** [comment]
@angus1225. I downloaded the kodi 18 nightly yesterday. Modify the file games.py into the zip file. After install pluggin, configure and with archive game run ok. (i don't try full time, only a few minutes). Win64 kodi version.

**Comment by ivankokan** [comment]
@yzfr1, can you please try to generate debug log that contains the error in original code, so we fix it?

**Comment by yzfr1** [comment]
Hi @ivankokan, i not receive error, i configure the video option for 720P 60FPS and when start stream, press "O" key to see info of stream and see than stream is 30FPS.

**Comment by ivankokan** [comment]
No, no, I referred on `generateCombinedThumbnail` part, not on 6000kbs/3000kbs. (I will concentrate on that later.)

> Thanks @MRLB for your answer.
> 
> i tryied with the new zip with the modified gmae.py like you suggested:
> Go to /src/games.py
> Change line 245 from
> thumbnail_url = utils.generateCombinedThumbnail(v, h)
> to
> thumbnail_url = ""
> 
> but i didnt work.
> 
> can you explain it to me better? Maybe i dont understand it well…
> Thanks



> **I try this fix and work.** But the fix have a problem... I put in config 720P 60FPS and 6000kbs of bitrate, but the stream always set 720P 30FPS and 3000Kbs. Any fix for this?? THX

Does it mean that you get the error with the official package? It would be great to get full log so we trace the issue.

**Comment by yzfr1** [comment]
@ivankokan, ok then how create a log??. But i see for @angus1225 the fix not work, for me the fix works in archive game (live not tested).

**Comment by ivankokan** [comment]
@yzfr1 There are two (or even three) problems here:

1. Issue with `generateCombinedThumbnail` part for which the games list is not generated at all.
@MRLB provided a fix? for it but I would like to get the detailed log when the official package is used so we eventually detect what exactly was the problem.

2. 6000kbs/3000Kbs - I experience that for some longer period (maybe even more than a year) but I was not bothered about it as my TV display is not so large. I will definitely concentrate on this one after we resolve the upper issue. But here we can at least say that plugin is working.

3. @angus1225 hears audio part but does not see video part.

In order to resolve 1. and 3. we should get the detailed debug log. You can generate it this way:
- Enable Debug logging (https://kodi.wiki/view/Log_file/Advanced#GUI_settings).
- Enable Debug under add-on settings.
- Make actions to get an error.
- Locate the log file (https://kodi.wiki/view/Log_file/Advanced#Log_files).
- Share it with us (https://kodi.wiki/view/Log_file/Advanced#So_what_do_I_do_with_this_thing.3F).

Also, very useful information is what platform you use, processor architecture etc.

**Comment by s00pecados** [comment]
here's the log:
[kodi.log](https://github.com/maxgalbu/xbmc.plugin.video.nba/files/2521249/kodi.log)
I did what @MRLB said on the firestick and I'm getting the same result as @angus1225. I hear the audio but no video. Hopefully someone can find a fix for this.

**Comment by ivankokan** [comment]
Issue 1. from my previous post:
No logs provided yet.

Issue 3. from my previous post:
Hi, @s00pecados. So you have the problem like @angus1225, can you install the suggested app (https://github.com/maxgalbu/xbmc.plugin.video.nba/issues/83#issuecomment-381194441) so we compare their Widevine certification levels?

**Comment by s00pecados** [comment]
I´m using the firestick version 2. It has Widevine L1 (I checked with the app).

**Comment by dwane3** [comment]
Win 7 x6, Leia Beta 4 x64,not working.. What?

Error Type: <type 'exceptions.WindowsError'>
                                            Error Contents: [Error 3] : 'C:\\Users\\\xd0\x90\xd0\xbb\xd0\xb5\xd0\xba\xd1\x81\xd0\xb5\xd0\xb9\\AppData\\Roaming\\Kodi\\cdm/*.*'
                                            Traceback (most recent call last):
                                              File "C:\Users\�������\AppData\Roaming\Kodi\addons\plugin.video.nba\main.py", line 9, in <module>
                                                from leaguepass import *
                                              File "C:\Users\�������\AppData\Roaming\Kodi\addons\plugin.video.nba\src\leaguepass.py", line 80, in <module>
                                                playGame()
                                              File "C:\Users\�������\AppData\Roaming\Kodi\addons\plugin.video.nba\src\games.py", line 322, in playGame
                                                if is_helper.check_inputstream():
                                              File "C:\Users\�������\AppData\Roaming\Kodi\addons\script.module.inputstreamhelper\lib\inputstreamhelper.py", line 763, in check_inputstream
                                                return self._check_drm()
                                              File "C:\Users\�������\AppData\Roaming\Kodi\addons\script.module.inputstreamhelper\lib\inputstreamhelper.py", line 734, in _check_drm
                                                if not self._has_widevine():
                                              File "C:\Users\�������\AppData\Roaming\Kodi\addons\script.module.inputstreamhelper\lib\inputstreamhelper.py", line 265, in _has_widevine
                                                if self._widevine_path():
                                              File "C:\Users\�������\AppData\Roaming\Kodi\addons\script.module.inputstreamhelper\lib\inputstreamhelper.py", line 108, in _widevine_path
                                                for filename in os.listdir(cls._ia_cdm_path()):
                                            WindowsError: [Error 3] : 'C:\\Users\\\xd0\x90\xd0\xbb\xd0\xb5\xd0\xba\xd1\x81\xd0\xb5\xd0\xb9\\AppData\\Roaming\\Kodi\\cdm/*.*'

**Comment by ivankokan** [comment]
@dwane3 Report it here: https://github.com/emilsvennesson/script.module.inputstreamhelper. (I would say that either the C:\Users\\xd0\x90\xd0\xbb\xd0\xb5\xd0\xba\xd1\x81\xd0\xb5\xd0\xb9\AppData\Roaming\Kodi\cdm/ folder does not exist or that non-ASCII characters are the root cause.)

**Also, let's keep this Issue thread only for Fire TV & live games, just as subject says.**

**Comment by yzfr1** [comment]
Hi, My config is:
Software:
Win 10 Pro april Update X64 with updates until today
Kodi Version: KodiSetup-20181028-f237c7e5-master-x64.exe

Hardware:
Motherboard: Gigabyte Z390 Gaming X
Processor: Intel Core i5 9600K
Graphics: Intel UHD 630 (i could try too with GTX 1070, now i have deattached)
Memory: 16GB Corsair Vengance DDR4-3000
SDD: Samsung 970 EVO 250GB.

Now, i install the plugin without modify, and start streaming with archive game. Still problem of bitrate.
[kodi.log](https://github.com/maxgalbu/xbmc.plugin.video.nba/files/2523250/kodi.log)

**Comment by ivankokan** [comment]
> Also, let's keep this Issue thread only for Fire TV & live games, just as subject says.

**Comment by cablegoon** [comment]
im getting these errors in regards to input stream
This is on a fire tv with the thumbnail edit and kodi v18
i now only get audio and no video

00:36:04.264 T:18446744072554752864 NOTICE: Creating InputStream
00:36:04.367 T:18446744072554752864 ERROR: AddOnLog: InputStream Adaptive: Key system request: com.widevine.alpha
00:36:05.728 T:18446744072506505032 NOTICE: PLEX.kodidb_functions: Did not find any file, abort

and 


00:35:04.938 T:18446744072551645968   ERROR: AddOnLog: InputStream Adaptive: NAL Unit exceeds subsample definition (nls: 4) 15466 -> 42
00:35:04.939 T:18446744072551645968   ERROR: AddOnLog: InputStream Adaptive: Decrypt Sample returns failure!

**Comment by ivankokan** [comment]
OK, let me summarize the status:
1. Thumbnail [Errno 22] Invalid argument issue is now being discussed and analyzed under #83.
2. Bitrates are being discussed and analyzed under #89.

**@angus1225, @s00pecados, @cablegoon Here we continue with Audio+ Video- issue.**

**Comment by joshjryan** [comment]
@ivankokan, now that I'm using your fork which handles the PIL issues, I can attempt to play archived games. When I do so, I get only audio (no video; just black).
See logs: http://paste.kodi.tv/ijeqojuduy
Interesting stuff starts around line 4920.
It loosk like the same NAL/subsample issue mentioned by @cablegoon.

Thanks again for all of your help, and let me know if I can help debug this any further.

[This issue](https://github.com/peak3d/inputstream.adaptive/issues/208) might be relevant.

**Comment by ivankokan** [comment]
Yes, that's another issue for Android. Let's keep track of inputstream.adaptive...

**Comment by cablegoon** [comment]
ok - so I just got a sheild and am having the same issue - I believe its an input stream error and not PIL related but lets see

**Comment by Lakersfan16** [comment]
I have the same problem. I only get the audio. Any fixes? Android TV

**Comment by ivankokan** [comment]
Follow the inputstream.adaptive issue @joshjryan referenced.

**Comment by joshjryan** [comment]
@lakersfan16, follow https://github.com/peak3d/inputstream.adaptive/issues/208

**Comment by lyossy** [comment]
hey guys
take a look at the "inputstream.adaptive"
forum for a solution .
I have it now showing video on chuwi hibook pro and cube iwork10 ( x86 atom , android 5.1 ) and mibox 3 ( amlogic s905x , androidtv 8.0 ) .
The issue is triggered by unexpected data structures that are valid , but look invalid to the addon .

**Comment by ivankokan** [comment]
It seems that the fix is available: https://github.com/peak3d/inputstream.adaptive/issues/208. Please update your inputstream.adaptive, and test.

**Comment by dwane3** [comment]
error update to version 2.3.13 in kodi from download zip,why?

**Comment by joshjryan** [comment]
@dwane3, try downloading the latest kodi nightly (instead of just updating inputstream.adaptive from the zip).  The latest kodi nightly has the new release of inputstream.adaptive.
http://mirrors.kodi.tv/nightlies/android/arm/master/

**Comment by cablegoon** [comment]
working again after a year - looks like the update to inputstream fixed it 
I guess we can close this now

**Comment by ivankokan** [comment]
@dwane3 FYI: https://github.com/emilsvennesson/script.module.inputstreamhelper/pull/42

**Comment by ivankokan** [comment]
@yzfr1 I guess you can close this one?

**Comment by yzfr1** [comment]
@ivankokan yes, sorry, i think i make a mistake post where not applicate, I not see "Issue" site.  Sorry!!!
Any solution to live games?

**Comment by ivankokan** [comment]
Close it there and read comments there as well.

**Comment by ivankokan** [comment]
@yzfr1, please close this one. If you still have some **recent** issues, please check whether #97, #98 or #99 help you before opening a new Issue.
